name: slack-blockify test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: slack-blockify test
        run: |
          echo "Running slack-blockify tests"
          npm run build
          npm test
          echo "Running tests completed"
